### ISSUE TITLE
Compat with Mariam's Soulsweapons for shield parry

### ISSUE THREAD

**Issue by NolanHewitt** [Partonetrain/botaniacombat#12]
Would it be possible to allow the shields from this mod to be made to work with the shield parry feature in [this mod?](https://github.com/mariumbacchus/Soulslike-Weaponry) I noticed other mod shields like the honey shield from bumblezone work with it, but the ones from this mod don't.

**Comment by Partonetrain** [comment]
From a quick glance, it looks like Soulslike Weaponry [checks for instances of ShieldItem](https://github.com/mariumbacchus/Soulslike-Weaponry/blob/499a0231f6dfb310873191b44a02bebf60d5a4b8/src/main/java/net/soulsweaponry/networking/C2S/ParryC2S.java#L22), which [Fabric Shield Lib items are not](https://github.com/StellarWind22/Fabric-Shield-Lib/blob/58daed2eff4f7055f19b66fb8af50235bcf1e365/src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldItem.java#L30).

A couple of solutions to this could possibly be:
* Soulslike Weapons changes to check for the `c:shields` tag instead of `instanceof ShieldItem`
* BotaniaCombat switches to a different shield library that uses vanilla ShieldItem class (unsure if this even exists)
* BotaniaCombat reimplements vanilla shield pattern related code (unlikely) so I can remove FabricShieldLib dep

My diagnosis may be incorrect, but I would recommend re-opening your Soulslike Weapons issue (or making a new one), because it's likely this effects all mods using Fabric Shield Lib.

**Comment by NolanHewitt** [comment]
Ah ok, thank you for the technical info. I've reopened my issue there and provided more info in it thanks to the info you gave me.
