### ISSUE TITLE
Angry Angry Bozu drops nothing in Survival

### ISSUE THREAD

**Issue by anoomolu** [Partonetrain/botaniacombat#13]
Hiya! I was playing around with the Angry Angry Bozu and noticed that when breaking it, it doesn't drop itself unlike the regular Bozu. Might be an issue with the block loot table, unless it's intentional and the Bozu is so full of rage that it simply disintegrates?

Also unrelated question while I'm here, would you be able to expand on what the updated Skadi bow does? Was reading through the new lang and saw something about fang-like structures, but I haven't seen anything of the sort, neither the cold effect when shooting myself or other mobs. Thanks again for keeping this mod alive and kicking ^^

**Comment by Partonetrain** [comment]
My bad, forgot to add a loot table.

I added two pixels to the Skadi's bow texture that are supposed to represent them, but they might need to be more prevalent to be clear.
The cold effect happens when meleeing a mob with the bow. It deals extra damage to mobs tagged with a vanilla tag (which I forget, but Blazes and Magma Cubes are in it) It instantly converts Skeletons. It's meant to be very situational, but now that you bring it up it might be *too* situational. Do you have any suggestions for it?

**Comment by anoomolu** [comment]
Oh I see, think I just misunderstood "arrow rest" as being where the arrow landed. The entry makes much more sense now, sorry 😭 

It's a neat easter egg, not sure if I can see any viable use for using a bow as a melee weapon though. The only extra drop Strays have is a weaker Slowness arrow than what can be produced from the bow anyways. 

As for ideas, the main one that comes to mind is one I suggested [here](https://github.com/Darkhax-Minecraft/Stronger-Snowballs/issues/5) for Snowballs - hitting a target increases their TicksFrozen counter. Maybe each arrow landed could instantly raise the counter by 200 or more, giving the player time to line up the next shot while the target is slowed and taking a freeze DoT. I'm not sure how strong the slow from freeze is, but the current slowness effect would likely need to be nerfed to strength 1 or 2 if not removed. This would still work with the mobs in #freeze_hurts_extra and would convert skeletons if they died to the damage from freezing.

Distantly related, would it be possible to have a 16x16 texture for the bow? It's very pretty but also pretty darn big when held, which might be the point but it feels a little funny when comparing with regular bows. Wouldn't mind commissioning it if you'd prefer.

**Comment by Partonetrain** [comment]
I like the adding TicksFrozen from arrows idea, but it would require adding a new arrow entity, or mixing into arrows. I'll look into it, though.
Converting skeletons is more annoying then you'd think, because they constantly check if they're in powder snow, and if they're not converted instantly, then their powder snow time is reset. In fact, they *can't* die from freezing.

I also forgot to mention - Power influences its melee damage on #freeze_hurts_extra mobs!

It's meant to be a larger bow, having been used by a jotunn. The Archers (RPG Series) mod (which I am personally using this mod alongside) features two-handed bows (and apparently the vanilla bow is one-handed). You're welcome to retexture it as you like but I don't see the need to provide a smaller texture with the mod. With BetterCombat, it is held like so:
![image](https://github.com/user-attachments/assets/419495ff-b62c-425a-8063-1254d78841b3)
as opposed to vanilla bows:
![image](https://github.com/user-attachments/assets/7c24549e-5fc6-41e4-b1d7-858842ecfa1d)
