### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by anoomolu** [Partonetrain/botaniacombat#2]
Hiya! This might be a long issue, so I've split it into two sections. If you disagree with any points I've raised then no worries. Been having fun playing around with all the new toys :)

### Some lang nitpicks
- `Gaia $(item)Gaia Greatsword$(0)` means that the word Gaia is repeated twice
- The text on page 2 of the Elementium Shield should point to `botaniacombat.page.elementium_shield1` rather than `elementium_banner_shield`. Alternatively, the lang entry could be adjusted to match the other pages. I'm unsure whether the item is meant to be called the Elementium Shield or Great Fairy Shield (I prefer the second tbh)
- Most `$(br)` macros could probably be replaced with `$(p)`, which makes new paragraphs and is usually what you see in Botania's lang for better readability. For example, with a `$(p)` in the above entry:
![image](https://github.com/Partonetrain/botaniacombat/assets/77850233/f48bdd22-0b0b-4d8d-9472-7676c1498bb1) 
Edit: I didn't notice that many entries use $(br2) which seems to work fine too ^^
- [BotaniaCombat] is visible on the Gaia Gifts page
- The Slaughtersaw mentions being usable only on mobs that drop meat (which has an unexpected $(thing) macro), but doesn't work on Hoglins. Probs how it should work, for balance reasons, but maybe clarify that it works on only passive mobs?

### Recipe adjustments
- I reckon the Manasteel Buckler and Elementium Shields could be made more expensive, considering the body of the shields is metal and not wood. Below is a possible recipe, alternatively maybe incorporating a Rune of Air to explain the faster swing speed?
![image](https://github.com/Partonetrain/botaniacombat/assets/77850233/b10fabae-aa3b-4e28-a36b-73def1e40c73)
Unsure about what a possible Elementium Shield recipe would be, maybe the same recipe as rails but Dreamwood flanked by Elementium Ingots instead?
- The Terra Shield (I think Terra Bulwark / Aegis goes hard) could use a Rune of Earth instead, and a different particle effect to the cloud? In my mind, it's the pinnacle of defensive utility and should be a sort of brick wall to mobs - maybe a shield bash would instead stun the enemy temporarily?

I had a question as well:
- Does the Crystal Crossbow actually reduce arrow spread? I use [Perfect Accuracy](https://modrinth.com/mod/perfect-accuracy) so I was wondering if I can remove this in favour of getting players to use better bows.

**Comment by Partonetrain** [comment]
1. Oops. Will be fixed in next release.
2. Oops again. Most Botania items have some kind of saying or reference under their crafting recipe, that's what Great Fairy Shield is meant to be.
3. `$(p)` is just a macro for `$(br2)`. Most places where `$(br)` is used, a `$(br2)` wouldn't fit. But I will go over it again.
4. This is intentional, making it clear that it's a BotaniaCombat mechanic, but now that you mention it, none of my other entries use it, so there's no point in having it
5. [Slaughtersaw *does* work on Hoglins](https://github.com/Partonetrain/botaniacombat/blob/main/src/main/resources/data/botaniacombat/tags/entity_types/meaty.json), it just doesn't instantly kill them for balance reasons. 4 hits with an unenchanted Slaughtersaw is still better than 5 hits with a Diamond Sword. It doesn't work on Zoglins. The entry is worded such that only _livestock_ will be instantly killed, but I will adjust it slightly to make it clear that it's not _only_ livestock.

edit: annoyingly it is actually 5 hits, the first hit actually doing 9.999998f - floating point imprecision? will bump up the damage slightly to ensure it is 4 hits

6. I like the recipes as they are. The justification for the Buckler increasing your swing speed is its lightness.
7. [The Crystal Crossbow has different, wider Multishot angles](https://github.com/Partonetrain/botaniacombat/blob/main/src/main/java/info/partonetrain/botaniacombat/item/ranged/CrystalCrossbowItem.java#L123-L132), not increased accuracy. I am unsure if Perfect Accuracy would effect modded weapons or how it would effect accuracy. 
![image](https://github.com/Partonetrain/botaniacombat/assets/19861808/caa45c7a-7dea-4594-89ee-05cd3995150f)

Also, Skadi's Bow has perfect accuracy.

I also just noticed that the shield/ranged weapon entries are loading even if the dependency isn't loaded.

**Comment by anoomolu** [comment]
Thank you for your reply! I guess players can always change recipes to suit their game/pack which is nice, and Skadi's Bow having perfect accuracy just makes sense, will defo be using it ^^

I don't see anything that hasn't been addressed so feel free to close this!
